2022-04-17 21:51:16.211 | DEBUG    | aria2p.interface:run:504 - Created new screen <tests.test_interface.MockedScreen object at 0x7f9614308b50>
2022-04-17 21:51:16.211 | DEBUG    | aria2p.interface:run:519 - Got event None
2022-04-17 21:51:16.211 | DEBUG    | aria2p.interface:run:535 - Tick! Updating data and rows
2022-04-17 21:51:16.241 | DEBUG    | aria2p.interface:run:542 - Refresh! Printing text
2022-04-17 21:51:16.247 | DEBUG    | aria2p.interface:run:519 - Got event KeyboardEvent: -102
2022-04-17 21:51:16.247 | DEBUG    | aria2p.interface:process_keyboard_event_main:676 - Triggered removal
2022-04-17 21:51:16.247 | DEBUG    | aria2p.interface:process_keyboard_event_main:677 - self.focused = 0
2022-04-17 21:51:16.247 | DEBUG    | aria2p.interface:process_keyboard_event_main:678 - len(self.data) = 2
2022-04-17 21:51:16.248 | DEBUG    | aria2p.interface:run:531 - Got event KeyboardEvent: -206
2022-04-17 21:51:16.248 | DEBUG    | aria2p.interface:process_keyboard_event_remove_ask:839 - Moving side focus down: 1
2022-04-17 21:51:16.248 | DEBUG    | aria2p.interface:run:531 - Got event KeyboardEvent: 10
2022-04-17 21:51:16.248 | DEBUG    | aria2p.interface:process_keyboard_event_remove_ask:817 - Validate removal
2022-04-17 21:51:16.248 | DEBUG    | aria2p.api:remove:465 - Try to remove download 0000000000000001
2022-04-17 21:51:16.254 | SUCCESS  | aria2p.api:remove:472 - Removed download 0000000000000001
2022-04-17 21:51:16.260 | DEBUG    | aria2p.api:remove:477 - Failed to remove download result 0000000000000001
2022-04-17 21:51:16.260 | TRACE    | aria2p.api:remove:478 - GID 0000000000000001 is not found
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw1-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f961879ea90>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f96188e7ce0>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f96187bd6d0>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f96187bd3d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f96187bde50>
    │    └ <function WorkerPool._perform_spawn at 0x7f96188e7ec0>
    └ <execnet.gateway_base.WorkerPool object at 0x7f96187bd6d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f96188e7ba0>
    └ <execnet.gateway_base.Reply object at 0x7f96187bde50>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f96187bd3d0>>
    └ <execnet.gateway_base.Reply object at 0x7f96187bde50>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7f96187c1290, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f961719ffd0>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7f961719f150>
    └ <_pytest.config.Config object at 0x7f961719ffd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f961719ffd0>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f961719ffd0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f961719ffd0>]
          │         └ <function pytest_cmdline_main at 0x7f9617401940>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f96174019e0>
           │            └ <_pytest.config.Config object at 0x7f961719ffd0>
           └ <function wrap_session at 0x7f96174018a0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7f961719ffd0>
    │       │            └ <function _main at 0x7f96174019e0>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7f961719f150>
    └ <_pytest.config.Config object at 0x7f961719ffd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f9616f88310>>
          └ <HookImpl plugin_name='140282607207184', plugin=<__channelexec__.WorkerInteractor object at 0x7f9616f88310>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [259]
    │    └ <function WorkerInteractor.run_one_test at 0x7f961719bf60>
    └ <__channelexec__.WorkerInteractor object at 0x7f9616f88310>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_run>
    │    │      │    │                            └ <Function test_remember_last_remove>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7f961719f150>
    │    └ <_pytest.config.Config object at 0x7f961719ffd0>
    └ <__channelexec__.WorkerInteractor object at 0x7f9616f88310>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remember_last_remove>, 'nextitem': <Function test_run>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remember_last_remove>, 'nextitem': <Function test_run>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>, <Function test_run>]
          │         └ <function pytest_runtest_protocol at 0x7f9616c3cf40>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_run>
              │               └ <Function test_remember_last_remove>
              └ <function runtestprotocol at 0x7f96173e3f60>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remember_last_remove>
    │       │      └ <function call_and_report at 0x7f9617400360>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_interface.py::test_remember_last_remove' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remember_last_remove>
           └ <function call_runtest_hook at 0x7f9617400540>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f9617400b80>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f961413bba0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remember_last_remove>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remember_last_remove>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remember_last_remove>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>]
          │         └ <function pytest_runtest_call at 0x7f9617400180>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f9617453560>
    └ <Function test_remember_last_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remember_last_remove>
    │    └ <property object at 0x7f9617537b00>
    └ <Function test_remember_last_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remember_last_remove>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remember_last_remove>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>]
          │         └ <function pytest_pyfunc_call at 0x7f9617450360>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-4/popen-gw1/test_remember_last_remove0'), 'port': 15222, 'monkeypatch':...
             └ <function test_remember_last_remove at 0x7f9614b98680>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 355, in test_remember_last_remove
    interface = run_interface(
                └ <function run_interface at 0x7f9614bb3560>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 98, in run_interface
    interface.run()
    │         └ <function Interface.run at 0x7f9615bda840>
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 523, in run
    self.process_event(event)
    │    │             └ KeyboardEvent: 10
    │    └ <function Interface.process_event at 0x7f9615bdaa20>
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 587, in process_event
    self.process_keyboard_event(event)
    │    │                      └ KeyboardEvent: 10
    │    └ <function Interface.process_keyboard_event at 0x7f9615bdaac0>
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 593, in process_keyboard_event
    self.state_mapping[self.state]["process_keyboard_event"](event)
    │    │             │    │                                └ KeyboardEvent: 10
    │    │             │    └ 3
    │    │             └ <aria2p.interface.Interface object at 0x7f96141b8050>
    │    └ {0: {'process_keyboard_event': <bound method Interface.process_keyboard_event_main of <aria2p.interface.Interface object at 0...
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 819, in process_keyboard_event_remove_ask
    self.remove_ask_rows[self.side_focused][1](self.follow)
    │    │               │    │                │    └ <aria2p.downloads.Download object at 0x7f961658d6d0>
    │    │               │    │                └ <aria2p.interface.Interface object at 0x7f96141b8050>
    │    │               │    └ 1
    │    │               └ <aria2p.interface.Interface object at 0x7f96141b8050>
    │    └ [('Remove', <function Interface.<lambda> at 0x7f9615bda520>), ('Remove with files', <function Interface.<lambda> at 0x7f9615b...
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 437, in <lambda>
    ("Remove with files", lambda d: d.remove(force=False, files=True)),
                                 │  │ └ <function Download.remove at 0x7f96160ad1c0>
                                 │  └ <aria2p.downloads.Download object at 0x7f961658d6d0>
                                 └ <aria2p.downloads.Download object at 0x7f961658d6d0>

  File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 1025, in remove
    result = self.api.remove([self], force=force, files=files)[0]
             │    │   │       │            │            └ True
             │    │   │       │            └ False
             │    │   │       └ <aria2p.downloads.Download object at 0x7f961658d6d0>
             │    │   └ <function API.remove at 0x7f96160ae480>
             │    └ API(Client(host='http://localhost', port=15222, secret='********'))
             └ <aria2p.downloads.Download object at 0x7f961658d6d0>

> File "/media/data/dev/aria2p/src/aria2p/api.py", line 475, in remove
    self.client.remove_download_result(download.gid)
    │    │      │                      │        └ <property object at 0x7f9616092de0>
    │    │      │                      └ <aria2p.downloads.Download object at 0x7f961658d6d0>
    │    │      └ <function Client.remove_download_result at 0x7f961602dd00>
    │    └ Client(host='http://localhost', port=15222, secret='********')
    └ API(Client(host='http://localhost', port=15222, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 1457, in remove_download_result
    return self.call(self.REMOVE_DOWNLOAD_RESULT, [gid])  # type: ignore
           │    │    │    │                        └ '0000000000000001'
           │    │    │    └ 'aria2.removeDownloadResult'
           │    │    └ Client(host='http://localhost', port=15222, secret='********')
           │    └ <function Client.call at 0x7f961602c720>
           └ Client(host='http://localhost', port=15222, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 262, in call
    return self.res_or_raise(self.post(payload))
           │    │            │    │    └ '{"jsonrpc": "2.0", "method": "aria2.removeDownloadResult", "id": -1, "params": ["0000000000000001"]}'
           │    │            │    └ <function Client.post at 0x7f961602c900>
           │    │            └ Client(host='http://localhost', port=15222, secret='********')
           │    └ <staticmethod(<function Client.res_or_raise at 0x7f961602ca40>)>
           └ Client(host='http://localhost', port=15222, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 389, in res_or_raise
    raise Client.response_as_exception(response)
          │      │                     └ {'id': -1, 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'GID 0000000000000001 is not found'}}
          │      └ <staticmethod(<function Client.response_as_exception at 0x7f961602c9a0>)>
          └ <class 'aria2p.client.Client'>

aria2p.client.ClientException: GID 0000000000000001 is not found
2022-04-17 21:51:16.270 | DEBUG    | aria2p.api:remove:494 - aria2 control file /tmp/pytest-of-pawamoy/pytest-4/popen-gw1/test_remember_last_remove0/5m.aria2 was not found
2022-04-17 21:51:16.271 | WARNING  | aria2p.downloads:root_files_paths:345 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-4/popen-gw1/test_remember_last_remove0'
2022-04-17 21:51:16.271 | TRACE    | aria2p.downloads:root_files_paths:346 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-4/popen-gw1/test_remember_last_remove0' OR one path is relative and the other is absolute.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw1-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f961879ea90>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f96188e7ce0>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f96187bd6d0>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f96187bd3d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f96187bde50>
    │    └ <function WorkerPool._perform_spawn at 0x7f96188e7ec0>
    └ <execnet.gateway_base.WorkerPool object at 0x7f96187bd6d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f96188e7ba0>
    └ <execnet.gateway_base.Reply object at 0x7f96187bde50>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f96187bd3d0>>
    └ <execnet.gateway_base.Reply object at 0x7f96187bde50>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7f96187c1290, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f961719ffd0>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7f961719f150>
    └ <_pytest.config.Config object at 0x7f961719ffd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f961719ffd0>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f961719ffd0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f961719ffd0>]
          │         └ <function pytest_cmdline_main at 0x7f9617401940>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f96174019e0>
           │            └ <_pytest.config.Config object at 0x7f961719ffd0>
           └ <function wrap_session at 0x7f96174018a0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7f961719ffd0>
    │       │            └ <function _main at 0x7f96174019e0>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7f961719f150>
    └ <_pytest.config.Config object at 0x7f961719ffd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f9616f88310>>
          └ <HookImpl plugin_name='140282607207184', plugin=<__channelexec__.WorkerInteractor object at 0x7f9616f88310>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [259]
    │    └ <function WorkerInteractor.run_one_test at 0x7f961719bf60>
    └ <__channelexec__.WorkerInteractor object at 0x7f9616f88310>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_run>
    │    │      │    │                            └ <Function test_remember_last_remove>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7f961719f150>
    │    └ <_pytest.config.Config object at 0x7f961719ffd0>
    └ <__channelexec__.WorkerInteractor object at 0x7f9616f88310>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remember_last_remove>, 'nextitem': <Function test_run>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remember_last_remove>, 'nextitem': <Function test_run>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>, <Function test_run>]
          │         └ <function pytest_runtest_protocol at 0x7f9616c3cf40>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_run>
              │               └ <Function test_remember_last_remove>
              └ <function runtestprotocol at 0x7f96173e3f60>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remember_last_remove>
    │       │      └ <function call_and_report at 0x7f9617400360>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_interface.py::test_remember_last_remove' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remember_last_remove>
           └ <function call_runtest_hook at 0x7f9617400540>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f9617400b80>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f961413bba0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remember_last_remove>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remember_last_remove>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remember_last_remove>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>]
          │         └ <function pytest_runtest_call at 0x7f9617400180>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f9617453560>
    └ <Function test_remember_last_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remember_last_remove>
    │    └ <property object at 0x7f9617537b00>
    └ <Function test_remember_last_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remember_last_remove>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f9617748b80>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f961719efd0>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remember_last_remove>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f9617703ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f961719efd0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remember_last_remove>]
          │         └ <function pytest_pyfunc_call at 0x7f9617450360>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-4/popen-gw1/test_remember_last_remove0'), 'port': 15222, 'monkeypatch':...
             └ <function test_remember_last_remove at 0x7f9614b98680>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 355, in test_remember_last_remove
    interface = run_interface(
                └ <function run_interface at 0x7f9614bb3560>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 98, in run_interface
    interface.run()
    │         └ <function Interface.run at 0x7f9615bda840>
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 523, in run
    self.process_event(event)
    │    │             └ KeyboardEvent: 10
    │    └ <function Interface.process_event at 0x7f9615bdaa20>
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 587, in process_event
    self.process_keyboard_event(event)
    │    │                      └ KeyboardEvent: 10
    │    └ <function Interface.process_keyboard_event at 0x7f9615bdaac0>
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 593, in process_keyboard_event
    self.state_mapping[self.state]["process_keyboard_event"](event)
    │    │             │    │                                └ KeyboardEvent: 10
    │    │             │    └ 3
    │    │             └ <aria2p.interface.Interface object at 0x7f96141b8050>
    │    └ {0: {'process_keyboard_event': <bound method Interface.process_keyboard_event_main of <aria2p.interface.Interface object at 0...
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 819, in process_keyboard_event_remove_ask
    self.remove_ask_rows[self.side_focused][1](self.follow)
    │    │               │    │                │    └ <aria2p.downloads.Download object at 0x7f961658d6d0>
    │    │               │    │                └ <aria2p.interface.Interface object at 0x7f96141b8050>
    │    │               │    └ 1
    │    │               └ <aria2p.interface.Interface object at 0x7f96141b8050>
    │    └ [('Remove', <function Interface.<lambda> at 0x7f9615bda520>), ('Remove with files', <function Interface.<lambda> at 0x7f9615b...
    └ <aria2p.interface.Interface object at 0x7f96141b8050>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 437, in <lambda>
    ("Remove with files", lambda d: d.remove(force=False, files=True)),
                                 │  │ └ <function Download.remove at 0x7f96160ad1c0>
                                 │  └ <aria2p.downloads.Download object at 0x7f961658d6d0>
                                 └ <aria2p.downloads.Download object at 0x7f961658d6d0>

  File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 1025, in remove
    result = self.api.remove([self], force=force, files=files)[0]
             │    │   │       │            │            └ True
             │    │   │       │            └ False
             │    │   │       └ <aria2p.downloads.Download object at 0x7f961658d6d0>
             │    │   └ <function API.remove at 0x7f96160ae480>
             │    └ API(Client(host='http://localhost', port=15222, secret='********'))
             └ <aria2p.downloads.Download object at 0x7f961658d6d0>

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 499, in remove
    self.remove_files([download], force=True)
    │    │             └ <aria2p.downloads.Download object at 0x7f961658d6d0>
    │    └ <staticmethod(<function API.remove_files at 0x7f96160aeca0>)>
    └ API(Client(host='http://localhost', port=15222, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 710, in remove_files
    for path in download.root_files_paths:
                │        └ <property object at 0x7f9616092d90>
                └ <aria2p.downloads.Download object at 0x7f961658d6d0>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 343, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7f9616093970>
                    │    │                └ <aria2p.downloads.Download object at 0x7f961658d6d0>
                    │    └ <property object at 0x7f9616092980>
                    └ <aria2p.downloads.File object at 0x7f96142f3890>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0a6/lib/python3.11/pathlib.py", line 726, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-4/popen-gw1/test_remember_last_remove0' OR one path is relative and the other is absolute.
2022-04-17 21:51:16.282 | DEBUG    | aria2p.interface:run:531 - Got event KeyboardEvent: -102
2022-04-17 21:51:16.282 | DEBUG    | aria2p.interface:process_keyboard_event_main:676 - Triggered removal
2022-04-17 21:51:16.283 | DEBUG    | aria2p.interface:process_keyboard_event_main:677 - self.focused = 0
2022-04-17 21:51:16.283 | DEBUG    | aria2p.interface:process_keyboard_event_main:678 - len(self.data) = 2
2022-04-17 21:51:16.283 | DEBUG    | aria2p.interface:run:531 - Got event KeyboardEvent: -1
2022-04-17 21:51:16.283 | DEBUG    | aria2p.interface:process_keyboard_event_remove_ask:811 - Canceling removal
2022-04-17 21:51:16.283 | DEBUG    | aria2p.interface:run:531 - Got event KeyboardEvent: 113
2022-04-17 21:51:16.283 | DEBUG    | aria2p.interface:run:525 - Received exit command
