2022-04-17 21:50:41.460 | DEBUG    | aria2p.api:remove:465 - Try to remove download 0000000000000001
2022-04-17 21:50:41.470 | SUCCESS  | aria2p.api:remove:472 - Removed download 0000000000000001
2022-04-17 21:50:41.478 | DEBUG    | aria2p.api:remove:477 - Failed to remove download result 0000000000000001
2022-04-17 21:50:41.478 | TRACE    | aria2p.api:remove:478 - GID 0000000000000001 is not found
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw5-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7fdc27868e80>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7fdc27736560>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
    └ <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
    │    └ <function WorkerPool._perform_spawn at 0x7fdc27736710>
    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7fdc277363b0>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7fdc275dbaa0, file "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7fdc2618d840>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7fdc2618d840>]
          │         └ <function pytest_cmdline_main at 0x7fdc262451b0>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7fdc26245240>
           │            └ <_pytest.config.Config object at 0x7fdc2618d840>
           └ <function wrap_session at 0x7fdc26245120>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    │       │            └ <function _main at 0x7fdc26245240>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
          └ <HookImpl plugin_name='140583506771152', plugin=<__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [369, 370]
    │    └ <function WorkerInteractor.run_one_test at 0x7fdc261908b0>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_remove_files_tree>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_remove_files_tree>]
          │         └ <function pytest_runtest_protocol at 0x7fdc25c57910>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.10...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_remove_files_tree>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7fdc26227c70>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7fdc262440d0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7fdc262441f0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7fdc26244430>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7fdc1f9e6ef0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7fdc26227e20>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7fdc26285cf0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7fdc2639e430>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7fdc263b7400>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'), 'port': 15170}
             └ <function test_remove_files_not_complete at 0x7fdc24e71cf0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 175, in test_remove_files_not_complete
    assert server.api.remove(downloads, files=True)
           │      │   │      └ [<aria2p.downloads.Download object at 0x7fdc1f84d0c0>, <aria2p.downloads.Download object at 0x7fdc1f84e4a0>]
           │      │   └ <function API.remove at 0x7fdc24f0bb50>
           │      └ API(Client(host='http://localhost', port=15170, secret='********'))
           └ <tests.conftest._Aria2Server object at 0x7fdc1fab6620>

> File "/media/data/dev/aria2p/src/aria2p/api.py", line 475, in remove
    self.client.remove_download_result(download.gid)
    │    │      │                      │        └ <property object at 0x7fdc24f04a90>
    │    │      │                      └ <aria2p.downloads.Download object at 0x7fdc1f84d0c0>
    │    │      └ <function Client.remove_download_result at 0x7fdc250ad510>
    │    └ Client(host='http://localhost', port=15170, secret='********')
    └ API(Client(host='http://localhost', port=15170, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 1457, in remove_download_result
    return self.call(self.REMOVE_DOWNLOAD_RESULT, [gid])  # type: ignore
           │    │    │    │                        └ '0000000000000001'
           │    │    │    └ 'aria2.removeDownloadResult'
           │    │    └ Client(host='http://localhost', port=15170, secret='********')
           │    └ <function Client.call at 0x7fdc250ac0d0>
           └ Client(host='http://localhost', port=15170, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 262, in call
    return self.res_or_raise(self.post(payload))
           │    │            │    │    └ '{"jsonrpc": "2.0", "method": "aria2.removeDownloadResult", "id": -1, "params": ["0000000000000001"]}'
           │    │            │    └ <function Client.post at 0x7fdc250ac280>
           │    │            └ Client(host='http://localhost', port=15170, secret='********')
           │    └ <staticmethod(<function Client.res_or_raise at 0x7fdc250ac3a0>)>
           └ Client(host='http://localhost', port=15170, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 389, in res_or_raise
    raise Client.response_as_exception(response)
          │      │                     └ {'id': -1, 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'GID 0000000000000001 is not found'}}
          │      └ <staticmethod(<function Client.response_as_exception at 0x7fdc250ac310>)>
          └ <class 'aria2p.client.Client'>

aria2p.client.ClientException: GID 0000000000000001 is not found
2022-04-17 21:50:41.488 | DEBUG    | aria2p.api:remove:494 - aria2 control file /tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0/5m.aria2 was not found
2022-04-17 21:50:41.489 | WARNING  | aria2p.downloads:root_files_paths:345 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'
2022-04-17 21:50:41.489 | TRACE    | aria2p.downloads:root_files_paths:346 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw5-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7fdc27868e80>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7fdc27736560>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
    └ <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
    │    └ <function WorkerPool._perform_spawn at 0x7fdc27736710>
    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7fdc277363b0>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7fdc275dbaa0, file "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7fdc2618d840>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7fdc2618d840>]
          │         └ <function pytest_cmdline_main at 0x7fdc262451b0>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7fdc26245240>
           │            └ <_pytest.config.Config object at 0x7fdc2618d840>
           └ <function wrap_session at 0x7fdc26245120>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    │       │            └ <function _main at 0x7fdc26245240>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
          └ <HookImpl plugin_name='140583506771152', plugin=<__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [369, 370]
    │    └ <function WorkerInteractor.run_one_test at 0x7fdc261908b0>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_remove_files_tree>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_remove_files_tree>]
          │         └ <function pytest_runtest_protocol at 0x7fdc25c57910>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.10...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_remove_files_tree>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7fdc26227c70>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7fdc262440d0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7fdc262441f0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7fdc26244430>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7fdc1f9e6ef0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7fdc26227e20>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7fdc26285cf0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7fdc2639e430>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7fdc263b7400>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'), 'port': 15170}
             └ <function test_remove_files_not_complete at 0x7fdc24e71cf0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 175, in test_remove_files_not_complete
    assert server.api.remove(downloads, files=True)
           │      │   │      └ [<aria2p.downloads.Download object at 0x7fdc1f84d0c0>, <aria2p.downloads.Download object at 0x7fdc1f84e4a0>]
           │      │   └ <function API.remove at 0x7fdc24f0bb50>
           │      └ API(Client(host='http://localhost', port=15170, secret='********'))
           └ <tests.conftest._Aria2Server object at 0x7fdc1fab6620>

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 499, in remove
    self.remove_files([download], force=True)
    │    │             └ <aria2p.downloads.Download object at 0x7fdc1f84d0c0>
    │    └ <staticmethod(<function API.remove_files at 0x7fdc24f0c310>)>
    └ API(Client(host='http://localhost', port=15170, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 710, in remove_files
    for path in download.root_files_paths:
                │        └ <property object at 0x7fdc24f04a40>
                └ <aria2p.downloads.Download object at 0x7fdc1f84d0c0>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 343, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7fdc24f056c0>
                    │    │                └ <aria2p.downloads.Download object at 0x7fdc1f84d0c0>
                    │    └ <property object at 0x7fdc24f045e0>
                    └ <aria2p.downloads.File object at 0x7fdc1f84d180>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.10.0/lib/python3.10/pathlib.py", line 816, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
2022-04-17 21:50:41.500 | DEBUG    | aria2p.api:remove:465 - Try to remove download 0000000000000002
2022-04-17 21:50:41.505 | SUCCESS  | aria2p.api:remove:472 - Removed download 0000000000000002
2022-04-17 21:50:41.509 | DEBUG    | aria2p.api:remove:477 - Failed to remove download result 0000000000000002
2022-04-17 21:50:41.509 | TRACE    | aria2p.api:remove:478 - GID 0000000000000002 is not found
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw5-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7fdc27868e80>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7fdc27736560>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
    └ <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
    │    └ <function WorkerPool._perform_spawn at 0x7fdc27736710>
    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7fdc277363b0>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7fdc275dbaa0, file "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7fdc2618d840>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7fdc2618d840>]
          │         └ <function pytest_cmdline_main at 0x7fdc262451b0>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7fdc26245240>
           │            └ <_pytest.config.Config object at 0x7fdc2618d840>
           └ <function wrap_session at 0x7fdc26245120>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    │       │            └ <function _main at 0x7fdc26245240>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
          └ <HookImpl plugin_name='140583506771152', plugin=<__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [369, 370]
    │    └ <function WorkerInteractor.run_one_test at 0x7fdc261908b0>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_remove_files_tree>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_remove_files_tree>]
          │         └ <function pytest_runtest_protocol at 0x7fdc25c57910>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.10...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_remove_files_tree>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7fdc26227c70>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7fdc262440d0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7fdc262441f0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7fdc26244430>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7fdc1f9e6ef0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7fdc26227e20>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7fdc26285cf0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7fdc2639e430>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7fdc263b7400>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'), 'port': 15170}
             └ <function test_remove_files_not_complete at 0x7fdc24e71cf0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 175, in test_remove_files_not_complete
    assert server.api.remove(downloads, files=True)
           │      │   │      └ [<aria2p.downloads.Download object at 0x7fdc1f84d0c0>, <aria2p.downloads.Download object at 0x7fdc1f84e4a0>]
           │      │   └ <function API.remove at 0x7fdc24f0bb50>
           │      └ API(Client(host='http://localhost', port=15170, secret='********'))
           └ <tests.conftest._Aria2Server object at 0x7fdc1fab6620>

> File "/media/data/dev/aria2p/src/aria2p/api.py", line 475, in remove
    self.client.remove_download_result(download.gid)
    │    │      │                      │        └ <property object at 0x7fdc24f04a90>
    │    │      │                      └ <aria2p.downloads.Download object at 0x7fdc1f84e4a0>
    │    │      └ <function Client.remove_download_result at 0x7fdc250ad510>
    │    └ Client(host='http://localhost', port=15170, secret='********')
    └ API(Client(host='http://localhost', port=15170, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 1457, in remove_download_result
    return self.call(self.REMOVE_DOWNLOAD_RESULT, [gid])  # type: ignore
           │    │    │    │                        └ '0000000000000002'
           │    │    │    └ 'aria2.removeDownloadResult'
           │    │    └ Client(host='http://localhost', port=15170, secret='********')
           │    └ <function Client.call at 0x7fdc250ac0d0>
           └ Client(host='http://localhost', port=15170, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 262, in call
    return self.res_or_raise(self.post(payload))
           │    │            │    │    └ '{"jsonrpc": "2.0", "method": "aria2.removeDownloadResult", "id": -1, "params": ["0000000000000002"]}'
           │    │            │    └ <function Client.post at 0x7fdc250ac280>
           │    │            └ Client(host='http://localhost', port=15170, secret='********')
           │    └ <staticmethod(<function Client.res_or_raise at 0x7fdc250ac3a0>)>
           └ Client(host='http://localhost', port=15170, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 389, in res_or_raise
    raise Client.response_as_exception(response)
          │      │                     └ {'id': -1, 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'GID 0000000000000002 is not found'}}
          │      └ <staticmethod(<function Client.response_as_exception at 0x7fdc250ac310>)>
          └ <class 'aria2p.client.Client'>

aria2p.client.ClientException: GID 0000000000000002 is not found
2022-04-17 21:50:41.517 | DEBUG    | aria2p.api:remove:494 - aria2 control file /tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0/6m.aria2 was not found
2022-04-17 21:50:41.518 | WARNING  | aria2p.downloads:root_files_paths:345 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'
2022-04-17 21:50:41.518 | TRACE    | aria2p.downloads:root_files_paths:346 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw5-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7fdc27868e80>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7fdc27736560>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
    └ <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
    │    └ <function WorkerPool._perform_spawn at 0x7fdc27736710>
    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7fdc277363b0>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7fdc275dbaa0, file "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7fdc2618d840>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7fdc2618d840>]
          │         └ <function pytest_cmdline_main at 0x7fdc262451b0>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7fdc26245240>
           │            └ <_pytest.config.Config object at 0x7fdc2618d840>
           └ <function wrap_session at 0x7fdc26245120>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    │       │            └ <function _main at 0x7fdc26245240>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
          └ <HookImpl plugin_name='140583506771152', plugin=<__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [369, 370]
    │    └ <function WorkerInteractor.run_one_test at 0x7fdc261908b0>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_remove_files_tree>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_remove_files_tree>]
          │         └ <function pytest_runtest_protocol at 0x7fdc25c57910>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.10...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_remove_files_tree>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7fdc26227c70>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7fdc262440d0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7fdc262441f0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7fdc26244430>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7fdc1f9e6ef0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7fdc26227e20>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7fdc26285cf0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7fdc2639e430>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7fdc263b7400>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'), 'port': 15170}
             └ <function test_remove_files_not_complete at 0x7fdc24e71cf0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 175, in test_remove_files_not_complete
    assert server.api.remove(downloads, files=True)
           │      │   │      └ [<aria2p.downloads.Download object at 0x7fdc1f84d0c0>, <aria2p.downloads.Download object at 0x7fdc1f84e4a0>]
           │      │   └ <function API.remove at 0x7fdc24f0bb50>
           │      └ API(Client(host='http://localhost', port=15170, secret='********'))
           └ <tests.conftest._Aria2Server object at 0x7fdc1fab6620>

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 499, in remove
    self.remove_files([download], force=True)
    │    │             └ <aria2p.downloads.Download object at 0x7fdc1f84e4a0>
    │    └ <staticmethod(<function API.remove_files at 0x7fdc24f0c310>)>
    └ API(Client(host='http://localhost', port=15170, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 710, in remove_files
    for path in download.root_files_paths:
                │        └ <property object at 0x7fdc24f04a40>
                └ <aria2p.downloads.Download object at 0x7fdc1f84e4a0>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 343, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7fdc24f056c0>
                    │    │                └ <aria2p.downloads.Download object at 0x7fdc1f84e4a0>
                    │    └ <property object at 0x7fdc24f045e0>
                    └ <aria2p.downloads.File object at 0x7fdc1f84d690>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.10.0/lib/python3.10/pathlib.py", line 816, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
2022-04-17 21:50:41.529 | WARNING  | aria2p.downloads:root_files_paths:345 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'
2022-04-17 21:50:41.529 | TRACE    | aria2p.downloads:root_files_paths:346 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw5-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7fdc27868e80>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7fdc27736560>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
    └ <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
    │    └ <function WorkerPool._perform_spawn at 0x7fdc27736710>
    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7fdc277363b0>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7fdc275dbaa0, file "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7fdc2618d840>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7fdc2618d840>]
          │         └ <function pytest_cmdline_main at 0x7fdc262451b0>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7fdc26245240>
           │            └ <_pytest.config.Config object at 0x7fdc2618d840>
           └ <function wrap_session at 0x7fdc26245120>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    │       │            └ <function _main at 0x7fdc26245240>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
          └ <HookImpl plugin_name='140583506771152', plugin=<__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [369, 370]
    │    └ <function WorkerInteractor.run_one_test at 0x7fdc261908b0>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_remove_files_tree>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_remove_files_tree>]
          │         └ <function pytest_runtest_protocol at 0x7fdc25c57910>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.10...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_remove_files_tree>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7fdc26227c70>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7fdc262440d0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7fdc262441f0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7fdc26244430>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7fdc1f9e6ef0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7fdc26227e20>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7fdc26285cf0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7fdc2639e430>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7fdc263b7400>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'), 'port': 15170}
             └ <function test_remove_files_not_complete at 0x7fdc24e71cf0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 177, in test_remove_files_not_complete
    for file in download.root_files_paths:
                │        └ <property object at 0x7fdc24f04a40>
                └ <aria2p.downloads.Download object at 0x7fdc1f84d0c0>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 343, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7fdc24f056c0>
                    │    │                └ <aria2p.downloads.Download object at 0x7fdc1f84d0c0>
                    │    └ <property object at 0x7fdc24f045e0>
                    └ <aria2p.downloads.File object at 0x7fdc1f84d180>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.10.0/lib/python3.10/pathlib.py", line 816, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
2022-04-17 21:50:41.537 | WARNING  | aria2p.downloads:root_files_paths:345 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'
2022-04-17 21:50:41.537 | TRACE    | aria2p.downloads:root_files_paths:346 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw5-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7fdc27868e80>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7fdc27736560>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
    └ <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
    │    └ <function WorkerPool._perform_spawn at 0x7fdc27736710>
    └ <execnet.gateway_base.WorkerPool object at 0x7fdc275b6620>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7fdc277363b0>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7fdc275b6140>>
    └ <execnet.gateway_base.Reply object at 0x7fdc275b6950>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7fdc275dbaa0, file "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7fdc2618d840>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7fdc2618d840>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7fdc2618d840>]
          │         └ <function pytest_cmdline_main at 0x7fdc262451b0>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7fdc26245240>
           │            └ <_pytest.config.Config object at 0x7fdc2618d840>
           └ <function wrap_session at 0x7fdc26245120>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    │       │            └ <function _main at 0x7fdc26245240>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    └ <_pytest.config.Config object at 0x7fdc2618d840>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
          └ <HookImpl plugin_name='140583506771152', plugin=<__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [369, 370]
    │    └ <function WorkerInteractor.run_one_test at 0x7fdc261908b0>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_remove_files_tree>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7fdc2614e170>
    │    └ <_pytest.config.Config object at 0x7fdc2618d840>
    └ <__channelexec__.WorkerInteractor object at 0x7fdc25fb7cd0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_remove_files_tree>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_remove_files_tree>]
          │         └ <function pytest_runtest_protocol at 0x7fdc25c57910>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.10...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_remove_files_tree>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7fdc26227c70>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7fdc262440d0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7fdc262441f0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7fdc26244430>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7fdc1f9e6ef0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7fdc26227e20>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7fdc26285cf0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7fdc2639e430>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fdc262d4670>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7fdc2666f910>
           └ <_pytest.config.PytestPluginManager object at 0x7fdc27607df0>
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7fdc263b7400>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.10/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0'), 'port': 15170}
             └ <function test_remove_files_not_complete at 0x7fdc24e71cf0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 177, in test_remove_files_not_complete
    for file in download.root_files_paths:
                │        └ <property object at 0x7fdc24f04a40>
                └ <aria2p.downloads.Download object at 0x7fdc1f84e4a0>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 343, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7fdc24f056c0>
                    │    │                └ <aria2p.downloads.Download object at 0x7fdc1f84e4a0>
                    │    └ <property object at 0x7fdc24f045e0>
                    └ <aria2p.downloads.File object at 0x7fdc1f84d690>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.10.0/lib/python3.10/pathlib.py", line 816, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-3/popen-gw5/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
